### ISSUE TITLE
DeFi apps

### ISSUE THREAD

**Issue by presence35** [phishfort/nighthawk-extension#8]
The actual apps for DeFi trading terminals (app.1inch.io & app.uniswap.org etc) are gray.  They should be recognized as trusted either because their root domain is trusted, or they should be added to the master approved list.

**Comment by vav12** [comment]
Hello! Thanks for your feedback

> The actual apps for DeFi trading terminals (app.1inch.io & app.uniswap.org etc) are gray. They should be recognized as trusted either because their root domain is trusted, or they should be added to the master approved list.

Thank you for your feedback! We are working on this.
